//! Request context management.
//!
//! Per-request state dict, contextvars integration, and built-in
//! context fields (req.id, req.user, req.trace).
//!
//! snek creates a new Python Context per request, avoiding the
//! Starlette BaseHTTPMiddleware bug where ContextVar propagation
//! breaks across threadpool executors.
//!
//! Sources:
//!   - Avoids Starlette's BaseHTTPMiddleware ContextVar bug
//!     (src/http/REFERENCES_middleware.md)

const ffi = @import("ffi.zig");

// ── RequestContext ──────────────────────────────────────────────────

/// Per-request context managed by the Zig runtime.
/// Holds request-scoped state and injects built-in fields.
///
/// Request (Zig) ←→ RequestContext (Python) ←→ DI resolution reads from Request
///
/// This is the Python-visible wrapper around the Zig-side Request's state.
/// The `zig_request` field points back to the owning Request, so both sides
/// share the same identity: built-in fields (id, user_id, trace_context)
/// live on the Request struct; this context adds Python dict state and
/// contextvars integration.
pub const RequestContext = struct {
    /// Python dict for arbitrary middleware-set state.
    state: ?*ffi.PyDict,

    /// Unique request ID (generated by snek).
    request_id: []const u8,

    /// User identity (set by auth middleware, null if unauthenticated).
    user: ?*ffi.PyObject,

    /// W3C traceparent header value for distributed tracing.
    trace: ?[]const u8,

    /// The Python Context object for this request's contextvars.
    py_context: ?*ffi.PyObject,

    /// Back-reference to the Zig-side Request that owns this context.
    /// The Request and RequestContext are the same object viewed from two sides.
    zig_request: ?*anyopaque,

    pub fn init(request_id: []const u8) RequestContext {
        return .{
            .state = null,
            .request_id = request_id,
            .user = null,
            .trace = null,
            .py_context = null,
            .zig_request = null,
        };
    }

    /// Create the Python Context for this request's contextvars.
    /// Called once per request before the handler is driven.
    /// Source: New Context per request avoids Starlette's BaseHTTPMiddleware
    /// ContextVar propagation bug (src/http/REFERENCES_middleware.md).
    pub fn createPyContext(self: *RequestContext) !void {
        _ = self;
        // Stub: call contextvars.copy_context() to create an isolated
        // Context, store in self.py_context.
    }

    /// Set a value in the request state dict.
    pub fn setState(self: *RequestContext, key: [*:0]const u8, value: *ffi.PyObject) !void {
        _ = .{ self, key, value };
    }

    /// Get a value from the request state dict.
    pub fn getState(self: *RequestContext, key: [*:0]const u8) ?*ffi.PyObject {
        _ = .{ self, key };
        return null;
    }

    /// Set the user identity (called by auth middleware).
    pub fn setUser(self: *RequestContext, user_obj: *ffi.PyObject) void {
        self.user = user_obj;
    }

    /// Set the W3C traceparent value.
    pub fn setTrace(self: *RequestContext, traceparent: []const u8) void {
        self.trace = traceparent;
    }

    pub fn deinit(self: *RequestContext) void {
        if (self.state) |s| {
            ffi.pyDecref(@ptrCast(s));
            self.state = null;
        }
        if (self.py_context) |ctx| {
            ffi.pyDecref(ctx);
            self.py_context = null;
        }
        if (self.user) |u| {
            ffi.pyDecref(u);
            self.user = null;
        }
    }
};

// ── ContextVar integration ──────────────────────────────────────────

/// Manages Python ContextVar instances for snek's built-in vars.
/// Created once at module init, used per-request.
pub const ContextVarIntegration = struct {
    /// ContextVar for the current request object.
    request_var: ?*ffi.PyObject,

    pub fn init() ContextVarIntegration {
        return .{ .request_var = null };
    }

    /// Create the ContextVar objects at module init time.
    pub fn setup(self: *ContextVarIntegration) !void {
        _ = self;
        // Stub: call contextvars.ContextVar("snek_request") etc.
    }

    /// Set the current request in the ContextVar for this request's Context.
    pub fn setCurrentRequest(self: *ContextVarIntegration, ctx: *RequestContext, request: *ffi.PyObject) !void {
        _ = .{ self, ctx, request };
    }

    pub fn deinit(self: *ContextVarIntegration) void {
        if (self.request_var) |v| {
            ffi.pyDecref(v);
            self.request_var = null;
        }
    }
};

// ── Tests ───────────────────────────────────────────────────────────

test "create request context" {}

test "request context state dict" {}

test "request context built-in fields" {}

test "contextvars isolation between requests" {}

test "contextvar integration setup" {}
