//! HTTP request parsing: JSON body, form data, multipart, streaming.
//!
//! Design: Two-arena memory model (conn_arena, req_arena from http.zig pattern).
//! Lazy query param and form body parsing. Streaming multipart parser:
//! callback-driven, 60-byte buffer (multipart-parser-c inspired), configurable
//! memory threshold for file uploads. Request state dict for middleware → handler
//! propagation. Generic over IO backend.
//!
//! Sources:
//!   - StreamingMultipart 60-byte buffer from multipart-parser-c
//!     (src/serve/REFERENCES.md)

const std = @import("std");
const context = @import("../python/context.zig");

/// Configuration for request parsing limits.
pub const RequestConfig = struct {
    /// Maximum body size in bytes (default 10MB).
    max_body_size: usize = 10 * 1024 * 1024,
    /// Maximum file upload size per field (default 50MB).
    max_file_size: usize = 50 * 1024 * 1024,
    /// Maximum total upload size across all fields (default 100MB).
    max_total_upload_size: usize = 100 * 1024 * 1024,
    /// Maximum number of multipart fields.
    max_fields: u32 = 100,
    /// Memory threshold: files smaller than this are kept in memory,
    /// larger files streamed to temp directory (default 1MB).
    memory_threshold: usize = 1024 * 1024,
    /// Temp directory for large file uploads.
    temp_dir: []const u8 = "/tmp",
    /// Maximum query string length.
    max_query_length: usize = 8192,
};

/// A parsed query parameter.
pub const QueryParam = struct {
    name: []const u8,
    value: []const u8,
};

/// An uploaded file, either in-memory or stored in a temp file.
pub const UploadedFile = struct {
    filename: []const u8,
    content_type: []const u8,
    /// In-memory data (null if file was streamed to disk).
    data: ?[]const u8,
    /// Temp file path (null if file is in memory).
    temp_path: ?[]const u8,
    size: usize,

    /// Whether this file is stored in memory or on disk.
    pub fn isInMemory(self: *const UploadedFile) bool {
        _ = .{self};
        return undefined;
    }
};

/// A single multipart field (form value or uploaded file).
pub const MultipartField = struct {
    name: []const u8,
    value: ?[]const u8,
    file: ?UploadedFile,
};

/// Parsed form data (application/x-www-form-urlencoded).
pub const FormData = struct {
    fields: []const [2][]const u8,
};

/// Request body variants.
pub const Body = union(enum) {
    json: []const u8,
    form: FormData,
    multipart: []MultipartField,
    raw: []const u8,
    stream: *anyopaque,
};

/// Streaming multipart parser callbacks.
/// Callback-driven, 60-byte internal buffer. Configurable memory threshold
/// determines whether file content is buffered in memory or streamed to disk.
/// Source: multipart-parser-c 60-byte buffer design (src/serve/REFERENCES.md).
pub const MultipartCallbacks = struct {
    on_part_begin: ?*const fn (*anyopaque) void = null,
    on_header_field: ?*const fn (*anyopaque, []const u8) void = null,
    on_header_value: ?*const fn (*anyopaque, []const u8) void = null,
    on_headers_complete: ?*const fn (*anyopaque) void = null,
    on_data: ?*const fn (*anyopaque, []const u8) void = null,
    on_part_end: ?*const fn (*anyopaque) void = null,
    on_complete: ?*const fn (*anyopaque) void = null,
    user_data: ?*anyopaque = null,
};

/// Streaming multipart parser state machine.
pub const StreamingMultipart = struct {
    boundary: []const u8,
    callbacks: MultipartCallbacks,
    config: RequestConfig,
    /// Internal 60-byte lookahead buffer.
    buf: [60]u8,
    buf_len: usize,
    state: enum {
        preamble,
        header_field,
        header_value,
        data,
        boundary_check,
        epilogue,
        done,
    },

    pub fn init(boundary: []const u8, callbacks: MultipartCallbacks, config: RequestConfig) StreamingMultipart {
        _ = .{ boundary, callbacks, config };
        return undefined;
    }

    /// Feed data to the parser. Invokes callbacks as parts are parsed.
    pub fn feed(self: *StreamingMultipart, data: []const u8) !void {
        _ = .{ self, data };
    }

    /// Signal end of input.
    pub fn finish(self: *StreamingMultipart) !void {
        _ = .{self};
    }
};

/// HTTP request with two-arena memory model. Generic over IO backend.
pub fn Request(comptime IO: type) type {
    return struct {
        const Self = @This();

        method: []const u8,
        path: []const u8,
        query_raw: ?[]const u8,
        headers: [][2][]const u8,
        body: ?Body,
        remote_addr: []const u8,
        io: *IO,

        /// Connection-scoped arena (lives for entire connection).
        conn_arena: *std.heap.ArenaAllocator,
        /// Request-scoped arena (reset between keepalive requests).
        req_arena: *std.heap.ArenaAllocator,

        // -- Built-in context fields --
        // Request (Zig) ←→ RequestContext (Python) ←→ DI resolution reads from Request

        /// Unique request ID (ULID, generated by snek).
        id: []const u8,
        /// Authenticated user ID (set by auth middleware, null if unauthenticated).
        user_id: ?[]const u8,
        /// W3C traceparent value for distributed tracing.
        trace_context: ?[]const u8,

        /// Pointer to the Python-side RequestContext that wraps this Request.
        /// Set once per request; allows middleware and DI to access either side.
        py_context: ?*context.RequestContext,

        // -- Lazy-parsed caches --

        /// Lazily parsed query parameters. Null until first access.
        _query_params: ?[]QueryParam,
        /// Lazily parsed form body. Null until first access.
        _form_data: ?FormData,
        /// Middleware → handler state propagation. Holds a pointer to the
        /// Python-side RequestContext state; use py_context.setState/getState.
        _state: ?*anyopaque,

        /// Lazily parse and return query parameters. Cached after first call.
        pub fn queryParams(self: *Self) ![]QueryParam {
            _ = .{self};
            return undefined;
        }

        /// Get a single query parameter by name.
        pub fn queryParam(self: *Self, name: []const u8) !?[]const u8 {
            _ = .{ self, name };
            return undefined;
        }

        /// Parse body as JSON bytes (raw JSON for the validator to consume).
        pub fn parseJson(self: *Self) ![]const u8 {
            _ = .{self};
            return undefined;
        }

        /// Lazily parse body as form data. Cached after first call.
        pub fn parseForm(self: *Self) !FormData {
            _ = .{self};
            return undefined;
        }

        /// Parse body as multipart using the streaming parser.
        pub fn parseMultipart(self: *Self, config: RequestConfig) ![]MultipartField {
            _ = .{ self, config };
            return undefined;
        }

        /// Get a streaming reader for the request body.
        pub fn bodyStream(self: *Self) !*anyopaque {
            _ = .{self};
            return undefined;
        }

        /// Get a header value by name (case-insensitive).
        pub fn header(self: *const Self, name: []const u8) ?[]const u8 {
            _ = .{ self, name };
            return undefined;
        }

        // -- Request state (middleware → handler propagation) --
        // Delegates to the Python-side RequestContext for state storage.

        /// Set a state value (used by middleware to pass data to handlers).
        /// Delegates to py_context if available, otherwise no-op.
        pub fn setState(self: *Self, key: [*:0]const u8, value: *anyopaque) void {
            if (self.py_context) |ctx| {
                const ffi_obj: *context.ffi.PyObject = @ptrCast(value);
                ctx.setState(key, ffi_obj) catch {};
            }
        }

        /// Get a state value by key.
        /// Delegates to py_context if available, otherwise returns null.
        pub fn getState(self: *const Self, key: [*:0]const u8) ?*anyopaque {
            if (self.py_context) |ctx| {
                if (ctx.getState(key)) |obj| return @ptrCast(obj);
            }
            return null;
        }
    };
}

test "parse query params" {}

test "lazy query param caching" {}

test "streaming multipart" {}

test "file upload threshold" {}

test "request state propagation" {}

test "header lookup case insensitive" {}

test "two arena memory model" {}
